### PR TITLE
add .env.example

### PR DESCRIPTION
**Pull request by mrforgotten**

### CODE REVIEW

**Comment by saravuthr** [comment]
@mrforgotten why we need .env for this project ?

**Review by saravuthr — CHANGES_REQUESTED** [review]
node env was already specified in npm.run dev command , isn't it ?

**Comment by mrforgotten** [comment]
Ok, I see. Sorry for wrong pr

**Comment by catflyflyfly** [comment]
Seems like @mrforgotten didn't aware that we use https://github.com/lorenwest/node-config for this repository, isn't it ?

**Comment by catflyflyfly** [comment]
That being said, @saravuthr is it really safe to keep `configs/production.json` in the code base? Isn't there the whole secret key ???

https://github.com/gu-tum-gun-aeng/med4all-patient-api/blob/main/src/configs/production.json

**Pull request closed without merging**
